name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: c-plus-plus-equals-c-plus-one/blog-post-workflow@master
        with:
          feed_list: "https://dev.to/feed/cplusplusequalscplusone,https://medium.com/feed/@aifos.si.prahs"
