name: Latest stack overflow activity
on:
  schedule:
    # Runs every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch:
jobs:
  update-readme-with-stack-overflow:
    name: Update this repo's README with latest activity from Devto
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "DEVTO"
          commit_message: "Updated readme with the latest devto data"
          feed_list: "https://dev.to/feed/cplusplusequalscplusone,https://medium.com/feed/@aifos.si.prahs"
